<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 30 Mar 2015 23:00:59 +0200
 */

$conf['title'] = 'Frankfurt RS-232 & TTL module';
$conf['template'] = 'simple_sidebar';
$conf['license'] = 'publicdomain';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['subscribers'] = 1;
$conf['notify'] = 'akhe@grodansparadis.com';
$conf['registernotify'] = 'akhe@grodansparadis.com';
$conf['mailfrom'] = 'akhe@grodansparadis.com';
$conf['sitemap'] = 1;
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>QnJpdHRhODIwNTA=';
$conf['plugin']['googleanalytics']['GAID'] = 'UA-61350556-1';

// end auto-generated content
